/*
 * DO NOT MODIFY. This file is automatically generated during the pre-build
 *                step by the lib_search utility
 */

"/Applications/ti/simplelink_cc2640r2_sdk_4_10_00_10/source/ti/ble5stack/blelib/cc26x0r2/ctrl/ll_xcxx.a"
"/Applications/ti/simplelink_cc2640r2_sdk_4_10_00_10/source/ti/ble5stack/blelib/cc26x0r2/ctrl/hci_xcxx.a"
"/Applications/ti/simplelink_cc2640r2_sdk_4_10_00_10/source/ti/ble5stack/blelib/cc26x0r2/hci_tl/hci_tl_full.a"
"/Applications/ti/simplelink_cc2640r2_sdk_4_10_00_10/source/ti/ble5stack/blelib/cc26x0r2/host/att_xcxx.a"
"/Applications/ti/simplelink_cc2640r2_sdk_4_10_00_10/source/ti/ble5stack/blelib/cc26x0r2/host/gap_xcxx.a"
"/Applications/ti/simplelink_cc2640r2_sdk_4_10_00_10/source/ti/ble5stack/blelib/cc26x0r2/host/profiles_xcxx.a"
"/Applications/ti/simplelink_cc2640r2_sdk_4_10_00_10/source/ti/ble5stack/blelib/cc26x0r2/host/gatt_xcxx.a"
"/Applications/ti/simplelink_cc2640r2_sdk_4_10_00_10/source/ti/ble5stack/blelib/cc26x0r2/host/smp_xcxx.a"
"/Applications/ti/simplelink_cc2640r2_sdk_4_10_00_10/source/ti/ble5stack/blelib/cc26x0r2/host/l2cap_xcxx.a"
"/Applications/ti/simplelink_cc2640r2_sdk_4_10_00_10/source/ti/ble5stack/blelib/cc26x0r2/host/sm_xcxx.a"
